// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConfigHandler.proto

package GrupoA.ConfigurationHandler.ConfigHandlerService;

public interface ConfigReponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GrupoA.ConfigurationHandler.ConfigHandlerService.ConfigReponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string configuration = 1;</code>
   */
  java.lang.String getConfiguration();
  /**
   * <code>string configuration = 1;</code>
   */
  com.google.protobuf.ByteString
      getConfigurationBytes();

  /**
   * <code>string id = 2;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 2;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
