// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConfigHandler.proto

package GrupoA.ConfigurationHandler.ConfigHandlerService;

public interface IntMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GrupoA.ConfigurationHandler.ConfigHandlerService.IntMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 Value = 1;</code>
   */
  int getValue();
}
