// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OSD.proto

package OSD;

public interface EmptyMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OSD.EmptyMessage)
    com.google.protobuf.MessageOrBuilder {
}
