// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OSDListener.proto

package GrupoA.StorageController.gRPCService.OSDListener;

public interface EmptyMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GrupoA.StorageController.gRPCService.OSDListener.EmptyMessage)
    com.google.protobuf.MessageOrBuilder {
}
