// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OSDListener.proto

package GrupoA.StorageController.gRPCService.OSDListener;

public interface OSDInSamePaGOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GrupoA.StorageController.gRPCService.OSDListener.OSDInSamePaG)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .GrupoA.StorageController.gRPCService.OSDListener.OSDDetails OSDs = 1;</code>
   */
  java.util.List<GrupoA.StorageController.gRPCService.OSDListener.OSDDetails> 
      getOSDsList();
  /**
   * <code>repeated .GrupoA.StorageController.gRPCService.OSDListener.OSDDetails OSDs = 1;</code>
   */
  GrupoA.StorageController.gRPCService.OSDListener.OSDDetails getOSDs(int index);
  /**
   * <code>repeated .GrupoA.StorageController.gRPCService.OSDListener.OSDDetails OSDs = 1;</code>
   */
  int getOSDsCount();
  /**
   * <code>repeated .GrupoA.StorageController.gRPCService.OSDListener.OSDDetails OSDs = 1;</code>
   */
  java.util.List<? extends GrupoA.StorageController.gRPCService.OSDListener.OSDDetailsOrBuilder> 
      getOSDsOrBuilderList();
  /**
   * <code>repeated .GrupoA.StorageController.gRPCService.OSDListener.OSDDetails OSDs = 1;</code>
   */
  GrupoA.StorageController.gRPCService.OSDListener.OSDDetailsOrBuilder getOSDsOrBuilder(
      int index);
}
