// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OSD.proto

package GrupoA.OSD.OSDService;

public interface BooleanMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GrupoA.OSD.OSDService.BooleanMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool result = 1;</code>
   */
  boolean getResult();
}
