// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OSD.proto

package GrupoA.OSD.OSDService;

public interface EmptyMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GrupoA.OSD.OSDService.EmptyMessage)
    com.google.protobuf.MessageOrBuilder {
}
