// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OSD.proto

package GrupoA.OSD.OSDService;

public interface GetObjectArgsWithMapOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GrupoA.OSD.OSDService.GetObjectArgsWithMap)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.GrupoA.OSD.OSDService.OSDInSamePaG OSDs = 1;</code>
   */
  boolean hasOSDs();
  /**
   * <code>.GrupoA.OSD.OSDService.OSDInSamePaG OSDs = 1;</code>
   */
  GrupoA.OSD.OSDService.OSDInSamePaG getOSDs();
  /**
   * <code>.GrupoA.OSD.OSDService.OSDInSamePaG OSDs = 1;</code>
   */
  GrupoA.OSD.OSDService.OSDInSamePaGOrBuilder getOSDsOrBuilder();

  /**
   * <code>.GrupoA.OSD.OSDService.GetObjectArgs GetObject = 2;</code>
   */
  boolean hasGetObject();
  /**
   * <code>.GrupoA.OSD.OSDService.GetObjectArgs GetObject = 2;</code>
   */
  GrupoA.OSD.OSDService.GetObjectArgs getGetObject();
  /**
   * <code>.GrupoA.OSD.OSDService.GetObjectArgs GetObject = 2;</code>
   */
  GrupoA.OSD.OSDService.GetObjectArgsOrBuilder getGetObjectOrBuilder();
}
