// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OSD.proto

package GrupoA.OSD.OSDService;

public interface GetObjectArgsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GrupoA.OSD.OSDService.GetObjectArgs)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 hash = 1;</code>
   */
  long getHash();
}
