// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OSD.proto

package GrupoA.OSD.OSDService;

public interface IntMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GrupoA.OSD.OSDService.IntMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 int = 1;</code>
   */
  long getInt();
}
