// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OSD.proto

package GrupoA.OSD.OSDService;

public interface MiniObjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GrupoA.OSD.OSDService.MiniObject)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 hash = 1;</code>
   */
  long getHash();

  /**
   * <code>bytes objectData = 2;</code>
   */
  com.google.protobuf.ByteString getObjectData();

  /**
   * <code>int32 startOffset = 3;</code>
   */
  int getStartOffset();

  /**
   * <code>int32 endOffset = 4;</code>
   */
  int getEndOffset();

  /**
   * <code>bool duplicate = 5;</code>
   */
  boolean getDuplicate();
}
