// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OSD.proto

package GrupoA.OSD.OSDService;

/**
 * Protobuf type {@code GrupoA.OSD.OSDService.MiniObject}
 */
public  final class MiniObject extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GrupoA.OSD.OSDService.MiniObject)
    MiniObjectOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MiniObject.newBuilder() to construct.
  private MiniObject(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MiniObject() {
    hash_ = 0L;
    objectData_ = com.google.protobuf.ByteString.EMPTY;
    startOffset_ = 0;
    endOffset_ = 0;
    duplicate_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MiniObject(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            hash_ = input.readInt64();
            break;
          }
          case 18: {

            objectData_ = input.readBytes();
            break;
          }
          case 24: {

            startOffset_ = input.readInt32();
            break;
          }
          case 32: {

            endOffset_ = input.readInt32();
            break;
          }
          case 40: {

            duplicate_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return GrupoA.OSD.OSDService.OSDProto.internal_static_GrupoA_OSD_OSDService_MiniObject_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return GrupoA.OSD.OSDService.OSDProto.internal_static_GrupoA_OSD_OSDService_MiniObject_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            GrupoA.OSD.OSDService.MiniObject.class, GrupoA.OSD.OSDService.MiniObject.Builder.class);
  }

  public static final int HASH_FIELD_NUMBER = 1;
  private long hash_;
  /**
   * <code>int64 hash = 1;</code>
   */
  public long getHash() {
    return hash_;
  }

  public static final int OBJECTDATA_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString objectData_;
  /**
   * <code>bytes objectData = 2;</code>
   */
  public com.google.protobuf.ByteString getObjectData() {
    return objectData_;
  }

  public static final int STARTOFFSET_FIELD_NUMBER = 3;
  private int startOffset_;
  /**
   * <code>int32 startOffset = 3;</code>
   */
  public int getStartOffset() {
    return startOffset_;
  }

  public static final int ENDOFFSET_FIELD_NUMBER = 4;
  private int endOffset_;
  /**
   * <code>int32 endOffset = 4;</code>
   */
  public int getEndOffset() {
    return endOffset_;
  }

  public static final int DUPLICATE_FIELD_NUMBER = 5;
  private boolean duplicate_;
  /**
   * <code>bool duplicate = 5;</code>
   */
  public boolean getDuplicate() {
    return duplicate_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (hash_ != 0L) {
      output.writeInt64(1, hash_);
    }
    if (!objectData_.isEmpty()) {
      output.writeBytes(2, objectData_);
    }
    if (startOffset_ != 0) {
      output.writeInt32(3, startOffset_);
    }
    if (endOffset_ != 0) {
      output.writeInt32(4, endOffset_);
    }
    if (duplicate_ != false) {
      output.writeBool(5, duplicate_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (hash_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, hash_);
    }
    if (!objectData_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, objectData_);
    }
    if (startOffset_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, startOffset_);
    }
    if (endOffset_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, endOffset_);
    }
    if (duplicate_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, duplicate_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof GrupoA.OSD.OSDService.MiniObject)) {
      return super.equals(obj);
    }
    GrupoA.OSD.OSDService.MiniObject other = (GrupoA.OSD.OSDService.MiniObject) obj;

    boolean result = true;
    result = result && (getHash()
        == other.getHash());
    result = result && getObjectData()
        .equals(other.getObjectData());
    result = result && (getStartOffset()
        == other.getStartOffset());
    result = result && (getEndOffset()
        == other.getEndOffset());
    result = result && (getDuplicate()
        == other.getDuplicate());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HASH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getHash());
    hash = (37 * hash) + OBJECTDATA_FIELD_NUMBER;
    hash = (53 * hash) + getObjectData().hashCode();
    hash = (37 * hash) + STARTOFFSET_FIELD_NUMBER;
    hash = (53 * hash) + getStartOffset();
    hash = (37 * hash) + ENDOFFSET_FIELD_NUMBER;
    hash = (53 * hash) + getEndOffset();
    hash = (37 * hash) + DUPLICATE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getDuplicate());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static GrupoA.OSD.OSDService.MiniObject parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GrupoA.OSD.OSDService.MiniObject parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GrupoA.OSD.OSDService.MiniObject parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GrupoA.OSD.OSDService.MiniObject parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GrupoA.OSD.OSDService.MiniObject parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GrupoA.OSD.OSDService.MiniObject parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GrupoA.OSD.OSDService.MiniObject parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static GrupoA.OSD.OSDService.MiniObject parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static GrupoA.OSD.OSDService.MiniObject parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static GrupoA.OSD.OSDService.MiniObject parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static GrupoA.OSD.OSDService.MiniObject parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static GrupoA.OSD.OSDService.MiniObject parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(GrupoA.OSD.OSDService.MiniObject prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GrupoA.OSD.OSDService.MiniObject}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GrupoA.OSD.OSDService.MiniObject)
      GrupoA.OSD.OSDService.MiniObjectOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GrupoA.OSD.OSDService.OSDProto.internal_static_GrupoA_OSD_OSDService_MiniObject_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GrupoA.OSD.OSDService.OSDProto.internal_static_GrupoA_OSD_OSDService_MiniObject_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GrupoA.OSD.OSDService.MiniObject.class, GrupoA.OSD.OSDService.MiniObject.Builder.class);
    }

    // Construct using GrupoA.OSD.OSDService.MiniObject.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      hash_ = 0L;

      objectData_ = com.google.protobuf.ByteString.EMPTY;

      startOffset_ = 0;

      endOffset_ = 0;

      duplicate_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return GrupoA.OSD.OSDService.OSDProto.internal_static_GrupoA_OSD_OSDService_MiniObject_descriptor;
    }

    @java.lang.Override
    public GrupoA.OSD.OSDService.MiniObject getDefaultInstanceForType() {
      return GrupoA.OSD.OSDService.MiniObject.getDefaultInstance();
    }

    @java.lang.Override
    public GrupoA.OSD.OSDService.MiniObject build() {
      GrupoA.OSD.OSDService.MiniObject result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public GrupoA.OSD.OSDService.MiniObject buildPartial() {
      GrupoA.OSD.OSDService.MiniObject result = new GrupoA.OSD.OSDService.MiniObject(this);
      result.hash_ = hash_;
      result.objectData_ = objectData_;
      result.startOffset_ = startOffset_;
      result.endOffset_ = endOffset_;
      result.duplicate_ = duplicate_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof GrupoA.OSD.OSDService.MiniObject) {
        return mergeFrom((GrupoA.OSD.OSDService.MiniObject)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(GrupoA.OSD.OSDService.MiniObject other) {
      if (other == GrupoA.OSD.OSDService.MiniObject.getDefaultInstance()) return this;
      if (other.getHash() != 0L) {
        setHash(other.getHash());
      }
      if (other.getObjectData() != com.google.protobuf.ByteString.EMPTY) {
        setObjectData(other.getObjectData());
      }
      if (other.getStartOffset() != 0) {
        setStartOffset(other.getStartOffset());
      }
      if (other.getEndOffset() != 0) {
        setEndOffset(other.getEndOffset());
      }
      if (other.getDuplicate() != false) {
        setDuplicate(other.getDuplicate());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      GrupoA.OSD.OSDService.MiniObject parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (GrupoA.OSD.OSDService.MiniObject) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long hash_ ;
    /**
     * <code>int64 hash = 1;</code>
     */
    public long getHash() {
      return hash_;
    }
    /**
     * <code>int64 hash = 1;</code>
     */
    public Builder setHash(long value) {
      
      hash_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 hash = 1;</code>
     */
    public Builder clearHash() {
      
      hash_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString objectData_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes objectData = 2;</code>
     */
    public com.google.protobuf.ByteString getObjectData() {
      return objectData_;
    }
    /**
     * <code>bytes objectData = 2;</code>
     */
    public Builder setObjectData(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      objectData_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes objectData = 2;</code>
     */
    public Builder clearObjectData() {
      
      objectData_ = getDefaultInstance().getObjectData();
      onChanged();
      return this;
    }

    private int startOffset_ ;
    /**
     * <code>int32 startOffset = 3;</code>
     */
    public int getStartOffset() {
      return startOffset_;
    }
    /**
     * <code>int32 startOffset = 3;</code>
     */
    public Builder setStartOffset(int value) {
      
      startOffset_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 startOffset = 3;</code>
     */
    public Builder clearStartOffset() {
      
      startOffset_ = 0;
      onChanged();
      return this;
    }

    private int endOffset_ ;
    /**
     * <code>int32 endOffset = 4;</code>
     */
    public int getEndOffset() {
      return endOffset_;
    }
    /**
     * <code>int32 endOffset = 4;</code>
     */
    public Builder setEndOffset(int value) {
      
      endOffset_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 endOffset = 4;</code>
     */
    public Builder clearEndOffset() {
      
      endOffset_ = 0;
      onChanged();
      return this;
    }

    private boolean duplicate_ ;
    /**
     * <code>bool duplicate = 5;</code>
     */
    public boolean getDuplicate() {
      return duplicate_;
    }
    /**
     * <code>bool duplicate = 5;</code>
     */
    public Builder setDuplicate(boolean value) {
      
      duplicate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool duplicate = 5;</code>
     */
    public Builder clearDuplicate() {
      
      duplicate_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GrupoA.OSD.OSDService.MiniObject)
  }

  // @@protoc_insertion_point(class_scope:GrupoA.OSD.OSDService.MiniObject)
  private static final GrupoA.OSD.OSDService.MiniObject DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new GrupoA.OSD.OSDService.MiniObject();
  }

  public static GrupoA.OSD.OSDService.MiniObject getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MiniObject>
      PARSER = new com.google.protobuf.AbstractParser<MiniObject>() {
    @java.lang.Override
    public MiniObject parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MiniObject(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MiniObject> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MiniObject> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public GrupoA.OSD.OSDService.MiniObject getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

