// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OSD.proto

package GrupoA.OSD.OSDService;

public interface ObjectDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GrupoA.OSD.OSDService.ObjectData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 hash = 1;</code>
   */
  long getHash();

  /**
   * <code>bytes objectData = 2;</code>
   */
  com.google.protobuf.ByteString getObjectData();
}
