// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OSD.proto

package GrupoA.OSD.OSDService;

public interface OSDDetailsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GrupoA.OSD.OSDService.OSDDetails)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Address = 1;</code>
   */
  java.lang.String getAddress();
  /**
   * <code>string Address = 1;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>int32 Port = 2;</code>
   */
  int getPort();

  /**
   * <code>bool leader = 3;</code>
   */
  boolean getLeader();
}
