// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OSD.proto

package GrupoA.OSD.OSDService;

/**
 * Protobuf type {@code GrupoA.OSD.OSDService.OSDInSamePaG}
 */
public  final class OSDInSamePaG extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GrupoA.OSD.OSDService.OSDInSamePaG)
    OSDInSamePaGOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OSDInSamePaG.newBuilder() to construct.
  private OSDInSamePaG(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OSDInSamePaG() {
    oSDs_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OSDInSamePaG(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              oSDs_ = new java.util.ArrayList<GrupoA.OSD.OSDService.OSDDetails>();
              mutable_bitField0_ |= 0x00000001;
            }
            oSDs_.add(
                input.readMessage(GrupoA.OSD.OSDService.OSDDetails.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        oSDs_ = java.util.Collections.unmodifiableList(oSDs_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return GrupoA.OSD.OSDService.OSDProto.internal_static_GrupoA_OSD_OSDService_OSDInSamePaG_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return GrupoA.OSD.OSDService.OSDProto.internal_static_GrupoA_OSD_OSDService_OSDInSamePaG_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            GrupoA.OSD.OSDService.OSDInSamePaG.class, GrupoA.OSD.OSDService.OSDInSamePaG.Builder.class);
  }

  public static final int OSDS_FIELD_NUMBER = 1;
  private java.util.List<GrupoA.OSD.OSDService.OSDDetails> oSDs_;
  /**
   * <code>repeated .GrupoA.OSD.OSDService.OSDDetails OSDs = 1;</code>
   */
  public java.util.List<GrupoA.OSD.OSDService.OSDDetails> getOSDsList() {
    return oSDs_;
  }
  /**
   * <code>repeated .GrupoA.OSD.OSDService.OSDDetails OSDs = 1;</code>
   */
  public java.util.List<? extends GrupoA.OSD.OSDService.OSDDetailsOrBuilder> 
      getOSDsOrBuilderList() {
    return oSDs_;
  }
  /**
   * <code>repeated .GrupoA.OSD.OSDService.OSDDetails OSDs = 1;</code>
   */
  public int getOSDsCount() {
    return oSDs_.size();
  }
  /**
   * <code>repeated .GrupoA.OSD.OSDService.OSDDetails OSDs = 1;</code>
   */
  public GrupoA.OSD.OSDService.OSDDetails getOSDs(int index) {
    return oSDs_.get(index);
  }
  /**
   * <code>repeated .GrupoA.OSD.OSDService.OSDDetails OSDs = 1;</code>
   */
  public GrupoA.OSD.OSDService.OSDDetailsOrBuilder getOSDsOrBuilder(
      int index) {
    return oSDs_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < oSDs_.size(); i++) {
      output.writeMessage(1, oSDs_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < oSDs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, oSDs_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof GrupoA.OSD.OSDService.OSDInSamePaG)) {
      return super.equals(obj);
    }
    GrupoA.OSD.OSDService.OSDInSamePaG other = (GrupoA.OSD.OSDService.OSDInSamePaG) obj;

    boolean result = true;
    result = result && getOSDsList()
        .equals(other.getOSDsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getOSDsCount() > 0) {
      hash = (37 * hash) + OSDS_FIELD_NUMBER;
      hash = (53 * hash) + getOSDsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static GrupoA.OSD.OSDService.OSDInSamePaG parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GrupoA.OSD.OSDService.OSDInSamePaG parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GrupoA.OSD.OSDService.OSDInSamePaG parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GrupoA.OSD.OSDService.OSDInSamePaG parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GrupoA.OSD.OSDService.OSDInSamePaG parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GrupoA.OSD.OSDService.OSDInSamePaG parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GrupoA.OSD.OSDService.OSDInSamePaG parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static GrupoA.OSD.OSDService.OSDInSamePaG parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static GrupoA.OSD.OSDService.OSDInSamePaG parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static GrupoA.OSD.OSDService.OSDInSamePaG parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static GrupoA.OSD.OSDService.OSDInSamePaG parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static GrupoA.OSD.OSDService.OSDInSamePaG parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(GrupoA.OSD.OSDService.OSDInSamePaG prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GrupoA.OSD.OSDService.OSDInSamePaG}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GrupoA.OSD.OSDService.OSDInSamePaG)
      GrupoA.OSD.OSDService.OSDInSamePaGOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GrupoA.OSD.OSDService.OSDProto.internal_static_GrupoA_OSD_OSDService_OSDInSamePaG_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GrupoA.OSD.OSDService.OSDProto.internal_static_GrupoA_OSD_OSDService_OSDInSamePaG_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GrupoA.OSD.OSDService.OSDInSamePaG.class, GrupoA.OSD.OSDService.OSDInSamePaG.Builder.class);
    }

    // Construct using GrupoA.OSD.OSDService.OSDInSamePaG.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getOSDsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (oSDsBuilder_ == null) {
        oSDs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        oSDsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return GrupoA.OSD.OSDService.OSDProto.internal_static_GrupoA_OSD_OSDService_OSDInSamePaG_descriptor;
    }

    @java.lang.Override
    public GrupoA.OSD.OSDService.OSDInSamePaG getDefaultInstanceForType() {
      return GrupoA.OSD.OSDService.OSDInSamePaG.getDefaultInstance();
    }

    @java.lang.Override
    public GrupoA.OSD.OSDService.OSDInSamePaG build() {
      GrupoA.OSD.OSDService.OSDInSamePaG result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public GrupoA.OSD.OSDService.OSDInSamePaG buildPartial() {
      GrupoA.OSD.OSDService.OSDInSamePaG result = new GrupoA.OSD.OSDService.OSDInSamePaG(this);
      int from_bitField0_ = bitField0_;
      if (oSDsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          oSDs_ = java.util.Collections.unmodifiableList(oSDs_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.oSDs_ = oSDs_;
      } else {
        result.oSDs_ = oSDsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof GrupoA.OSD.OSDService.OSDInSamePaG) {
        return mergeFrom((GrupoA.OSD.OSDService.OSDInSamePaG)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(GrupoA.OSD.OSDService.OSDInSamePaG other) {
      if (other == GrupoA.OSD.OSDService.OSDInSamePaG.getDefaultInstance()) return this;
      if (oSDsBuilder_ == null) {
        if (!other.oSDs_.isEmpty()) {
          if (oSDs_.isEmpty()) {
            oSDs_ = other.oSDs_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureOSDsIsMutable();
            oSDs_.addAll(other.oSDs_);
          }
          onChanged();
        }
      } else {
        if (!other.oSDs_.isEmpty()) {
          if (oSDsBuilder_.isEmpty()) {
            oSDsBuilder_.dispose();
            oSDsBuilder_ = null;
            oSDs_ = other.oSDs_;
            bitField0_ = (bitField0_ & ~0x00000001);
            oSDsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getOSDsFieldBuilder() : null;
          } else {
            oSDsBuilder_.addAllMessages(other.oSDs_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      GrupoA.OSD.OSDService.OSDInSamePaG parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (GrupoA.OSD.OSDService.OSDInSamePaG) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<GrupoA.OSD.OSDService.OSDDetails> oSDs_ =
      java.util.Collections.emptyList();
    private void ensureOSDsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        oSDs_ = new java.util.ArrayList<GrupoA.OSD.OSDService.OSDDetails>(oSDs_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        GrupoA.OSD.OSDService.OSDDetails, GrupoA.OSD.OSDService.OSDDetails.Builder, GrupoA.OSD.OSDService.OSDDetailsOrBuilder> oSDsBuilder_;

    /**
     * <code>repeated .GrupoA.OSD.OSDService.OSDDetails OSDs = 1;</code>
     */
    public java.util.List<GrupoA.OSD.OSDService.OSDDetails> getOSDsList() {
      if (oSDsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(oSDs_);
      } else {
        return oSDsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .GrupoA.OSD.OSDService.OSDDetails OSDs = 1;</code>
     */
    public int getOSDsCount() {
      if (oSDsBuilder_ == null) {
        return oSDs_.size();
      } else {
        return oSDsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .GrupoA.OSD.OSDService.OSDDetails OSDs = 1;</code>
     */
    public GrupoA.OSD.OSDService.OSDDetails getOSDs(int index) {
      if (oSDsBuilder_ == null) {
        return oSDs_.get(index);
      } else {
        return oSDsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .GrupoA.OSD.OSDService.OSDDetails OSDs = 1;</code>
     */
    public Builder setOSDs(
        int index, GrupoA.OSD.OSDService.OSDDetails value) {
      if (oSDsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOSDsIsMutable();
        oSDs_.set(index, value);
        onChanged();
      } else {
        oSDsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .GrupoA.OSD.OSDService.OSDDetails OSDs = 1;</code>
     */
    public Builder setOSDs(
        int index, GrupoA.OSD.OSDService.OSDDetails.Builder builderForValue) {
      if (oSDsBuilder_ == null) {
        ensureOSDsIsMutable();
        oSDs_.set(index, builderForValue.build());
        onChanged();
      } else {
        oSDsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GrupoA.OSD.OSDService.OSDDetails OSDs = 1;</code>
     */
    public Builder addOSDs(GrupoA.OSD.OSDService.OSDDetails value) {
      if (oSDsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOSDsIsMutable();
        oSDs_.add(value);
        onChanged();
      } else {
        oSDsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .GrupoA.OSD.OSDService.OSDDetails OSDs = 1;</code>
     */
    public Builder addOSDs(
        int index, GrupoA.OSD.OSDService.OSDDetails value) {
      if (oSDsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOSDsIsMutable();
        oSDs_.add(index, value);
        onChanged();
      } else {
        oSDsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .GrupoA.OSD.OSDService.OSDDetails OSDs = 1;</code>
     */
    public Builder addOSDs(
        GrupoA.OSD.OSDService.OSDDetails.Builder builderForValue) {
      if (oSDsBuilder_ == null) {
        ensureOSDsIsMutable();
        oSDs_.add(builderForValue.build());
        onChanged();
      } else {
        oSDsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GrupoA.OSD.OSDService.OSDDetails OSDs = 1;</code>
     */
    public Builder addOSDs(
        int index, GrupoA.OSD.OSDService.OSDDetails.Builder builderForValue) {
      if (oSDsBuilder_ == null) {
        ensureOSDsIsMutable();
        oSDs_.add(index, builderForValue.build());
        onChanged();
      } else {
        oSDsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GrupoA.OSD.OSDService.OSDDetails OSDs = 1;</code>
     */
    public Builder addAllOSDs(
        java.lang.Iterable<? extends GrupoA.OSD.OSDService.OSDDetails> values) {
      if (oSDsBuilder_ == null) {
        ensureOSDsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, oSDs_);
        onChanged();
      } else {
        oSDsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .GrupoA.OSD.OSDService.OSDDetails OSDs = 1;</code>
     */
    public Builder clearOSDs() {
      if (oSDsBuilder_ == null) {
        oSDs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        oSDsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .GrupoA.OSD.OSDService.OSDDetails OSDs = 1;</code>
     */
    public Builder removeOSDs(int index) {
      if (oSDsBuilder_ == null) {
        ensureOSDsIsMutable();
        oSDs_.remove(index);
        onChanged();
      } else {
        oSDsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .GrupoA.OSD.OSDService.OSDDetails OSDs = 1;</code>
     */
    public GrupoA.OSD.OSDService.OSDDetails.Builder getOSDsBuilder(
        int index) {
      return getOSDsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .GrupoA.OSD.OSDService.OSDDetails OSDs = 1;</code>
     */
    public GrupoA.OSD.OSDService.OSDDetailsOrBuilder getOSDsOrBuilder(
        int index) {
      if (oSDsBuilder_ == null) {
        return oSDs_.get(index);  } else {
        return oSDsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .GrupoA.OSD.OSDService.OSDDetails OSDs = 1;</code>
     */
    public java.util.List<? extends GrupoA.OSD.OSDService.OSDDetailsOrBuilder> 
         getOSDsOrBuilderList() {
      if (oSDsBuilder_ != null) {
        return oSDsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(oSDs_);
      }
    }
    /**
     * <code>repeated .GrupoA.OSD.OSDService.OSDDetails OSDs = 1;</code>
     */
    public GrupoA.OSD.OSDService.OSDDetails.Builder addOSDsBuilder() {
      return getOSDsFieldBuilder().addBuilder(
          GrupoA.OSD.OSDService.OSDDetails.getDefaultInstance());
    }
    /**
     * <code>repeated .GrupoA.OSD.OSDService.OSDDetails OSDs = 1;</code>
     */
    public GrupoA.OSD.OSDService.OSDDetails.Builder addOSDsBuilder(
        int index) {
      return getOSDsFieldBuilder().addBuilder(
          index, GrupoA.OSD.OSDService.OSDDetails.getDefaultInstance());
    }
    /**
     * <code>repeated .GrupoA.OSD.OSDService.OSDDetails OSDs = 1;</code>
     */
    public java.util.List<GrupoA.OSD.OSDService.OSDDetails.Builder> 
         getOSDsBuilderList() {
      return getOSDsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        GrupoA.OSD.OSDService.OSDDetails, GrupoA.OSD.OSDService.OSDDetails.Builder, GrupoA.OSD.OSDService.OSDDetailsOrBuilder> 
        getOSDsFieldBuilder() {
      if (oSDsBuilder_ == null) {
        oSDsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            GrupoA.OSD.OSDService.OSDDetails, GrupoA.OSD.OSDService.OSDDetails.Builder, GrupoA.OSD.OSDService.OSDDetailsOrBuilder>(
                oSDs_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        oSDs_ = null;
      }
      return oSDsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GrupoA.OSD.OSDService.OSDInSamePaG)
  }

  // @@protoc_insertion_point(class_scope:GrupoA.OSD.OSDService.OSDInSamePaG)
  private static final GrupoA.OSD.OSDService.OSDInSamePaG DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new GrupoA.OSD.OSDService.OSDInSamePaG();
  }

  public static GrupoA.OSD.OSDService.OSDInSamePaG getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OSDInSamePaG>
      PARSER = new com.google.protobuf.AbstractParser<OSDInSamePaG>() {
    @java.lang.Override
    public OSDInSamePaG parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OSDInSamePaG(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OSDInSamePaG> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OSDInSamePaG> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public GrupoA.OSD.OSDService.OSDInSamePaG getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

