// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OSD.proto

package GrupoA.OSD.OSDService;

public final class OSDProto {
  private OSDProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GrupoA_OSD_OSDService_OSDDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GrupoA_OSD_OSDService_OSDDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GrupoA_OSD_OSDService_OSDInSamePaG_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GrupoA_OSD_OSDService_OSDInSamePaG_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GrupoA_OSD_OSDService_MiniObject_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GrupoA_OSD_OSDService_MiniObject_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GrupoA_OSD_OSDService_GetObjectArgs_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GrupoA_OSD_OSDService_GetObjectArgs_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GrupoA_OSD_OSDService_ObjectData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GrupoA_OSD_OSDService_ObjectData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GrupoA_OSD_OSDService_BooleanMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GrupoA_OSD_OSDService_BooleanMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GrupoA_OSD_OSDService_EmptyMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GrupoA_OSD_OSDService_EmptyMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tOSD.proto\022\025GrupoA.OSD.OSDService\";\n\nOS" +
      "DDetails\022\017\n\007Address\030\001 \001(\t\022\014\n\004Port\030\002 \001(\005\022" +
      "\016\n\006leader\030\003 \001(\010\"?\n\014OSDInSamePaG\022/\n\004OSDs\030" +
      "\001 \003(\0132!.GrupoA.OSD.OSDService.OSDDetails" +
      "\"i\n\nMiniObject\022\014\n\004hash\030\001 \001(\003\022\022\n\nobjectDa" +
      "ta\030\002 \001(\014\022\023\n\013startOffset\030\003 \001(\005\022\021\n\tendOffs" +
      "et\030\004 \001(\005\022\021\n\tduplicate\030\005 \001(\010\"Y\n\rGetObject" +
      "Args\022\014\n\004hash\030\001 \001(\003\022\026\n\016relativeOffset\030\002 \001" +
      "(\003\022\014\n\004size\030\003 \001(\003\022\024\n\014hasDuplicate\030\004 \001(\010\"1" +
      "\n\nObjectData\022\017\n\007success\030\001 \001(\010\022\022\n\nobjectD" +
      "ata\030\002 \001(\014\" \n\016BooleanMessage\022\016\n\006result\030\001 " +
      "\001(\010\"\016\n\014EmptyMessage2\376\004\n\003OSD\022U\n\tputObject" +
      "\022!.GrupoA.OSD.OSDService.ObjectData\032#.Gr" +
      "upoA.OSD.OSDService.EmptyMessage\"\000\022[\n\017wr" +
      "iteMiniObject\022!.GrupoA.OSD.OSDService.Mi" +
      "niObject\032#.GrupoA.OSD.OSDService.EmptyMe" +
      "ssage\"\000\022[\n\016readMiniObject\022$.GrupoA.OSD.O" +
      "SDService.GetObjectArgs\032!.GrupoA.OSD.OSD" +
      "Service.ObjectData\"\000\022V\n\tgetObject\022$.Grup" +
      "oA.OSD.OSDService.GetObjectArgs\032!.GrupoA" +
      ".OSD.OSDService.ObjectData\"\000\022T\n\004ping\022#.G" +
      "rupoA.OSD.OSDService.EmptyMessage\032%.Grup" +
      "oA.OSD.OSDService.BooleanMessage\"\000\022[\n\rpu" +
      "shMapUpdate\022#.GrupoA.OSD.OSDService.OSDI" +
      "nSamePaG\032#.GrupoA.OSD.OSDService.EmptyMe" +
      "ssage\"\000\022[\n\014deleteObject\022$.GrupoA.OSD.OSD" +
      "Service.GetObjectArgs\032#.GrupoA.OSD.OSDSe" +
      "rvice.EmptyMessage\"\000B\020B\010OSDProtoP\001\242\002\001Ob\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_GrupoA_OSD_OSDService_OSDDetails_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GrupoA_OSD_OSDService_OSDDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GrupoA_OSD_OSDService_OSDDetails_descriptor,
        new java.lang.String[] { "Address", "Port", "Leader", });
    internal_static_GrupoA_OSD_OSDService_OSDInSamePaG_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GrupoA_OSD_OSDService_OSDInSamePaG_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GrupoA_OSD_OSDService_OSDInSamePaG_descriptor,
        new java.lang.String[] { "OSDs", });
    internal_static_GrupoA_OSD_OSDService_MiniObject_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GrupoA_OSD_OSDService_MiniObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GrupoA_OSD_OSDService_MiniObject_descriptor,
        new java.lang.String[] { "Hash", "ObjectData", "StartOffset", "EndOffset", "Duplicate", });
    internal_static_GrupoA_OSD_OSDService_GetObjectArgs_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_GrupoA_OSD_OSDService_GetObjectArgs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GrupoA_OSD_OSDService_GetObjectArgs_descriptor,
        new java.lang.String[] { "Hash", "RelativeOffset", "Size", "HasDuplicate", });
    internal_static_GrupoA_OSD_OSDService_ObjectData_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_GrupoA_OSD_OSDService_ObjectData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GrupoA_OSD_OSDService_ObjectData_descriptor,
        new java.lang.String[] { "Success", "ObjectData", });
    internal_static_GrupoA_OSD_OSDService_BooleanMessage_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_GrupoA_OSD_OSDService_BooleanMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GrupoA_OSD_OSDService_BooleanMessage_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_GrupoA_OSD_OSDService_EmptyMessage_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_GrupoA_OSD_OSDService_EmptyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GrupoA_OSD_OSDService_EmptyMessage_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
