// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FileSystem.proto

package GrupoA.StorageController.gRPCService.FileSystem;

public interface BooleanMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GrupoA.StorageController.gRPCService.FileSystem.BooleanMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool result = 1;</code>
   */
  boolean getResult();
}
