// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FileSystem.proto

package GrupoA.StorageController.gRPCService.FileSystem;

public interface CreateFileArgsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GrupoA.StorageController.gRPCService.FileSystem.CreateFileArgs)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string path = 1;</code>
   */
  java.lang.String getPath();
  /**
   * <code>string path = 1;</code>
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <code>int64 mode = 2;</code>
   */
  long getMode();

  /**
   * <code>int64 uid = 3;</code>
   */
  long getUid();

  /**
   * <code>int64 gid = 4;</code>
   */
  long getGid();
}
