// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FileSystem.proto

package GrupoA.StorageController.gRPCService.FileSystem;

public interface DirContentsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GrupoA.StorageController.gRPCService.FileSystem.DirContents)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();

  /**
   * <code>int64 parentINode = 2;</code>
   */
  long getParentINode();

  /**
   * <code>int64 INode = 3;</code>
   */
  long getINode();

  /**
   * <code>repeated .GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content Contents = 4;</code>
   */
  java.util.List<GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content> 
      getContentsList();
  /**
   * <code>repeated .GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content Contents = 4;</code>
   */
  GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content getContents(int index);
  /**
   * <code>repeated .GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content Contents = 4;</code>
   */
  int getContentsCount();
  /**
   * <code>repeated .GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content Contents = 4;</code>
   */
  java.util.List<? extends GrupoA.StorageController.gRPCService.FileSystem.DirContents.ContentOrBuilder> 
      getContentsOrBuilderList();
  /**
   * <code>repeated .GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content Contents = 4;</code>
   */
  GrupoA.StorageController.gRPCService.FileSystem.DirContents.ContentOrBuilder getContentsOrBuilder(
      int index);
}
