// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FileSystem.proto

package GrupoA.StorageController.gRPCService.FileSystem;

/**
 * Protobuf type {@code GrupoA.StorageController.gRPCService.FileSystem.DirContents}
 */
public  final class DirContents extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GrupoA.StorageController.gRPCService.FileSystem.DirContents)
    DirContentsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DirContents.newBuilder() to construct.
  private DirContents(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DirContents() {
    success_ = false;
    parentINode_ = 0L;
    iNode_ = 0L;
    contents_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DirContents(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            success_ = input.readBool();
            break;
          }
          case 16: {

            parentINode_ = input.readInt64();
            break;
          }
          case 24: {

            iNode_ = input.readInt64();
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              contents_ = new java.util.ArrayList<GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content>();
              mutable_bitField0_ |= 0x00000008;
            }
            contents_.add(
                input.readMessage(GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        contents_ = java.util.Collections.unmodifiableList(contents_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return GrupoA.StorageController.gRPCService.FileSystem.FileSystemProto.internal_static_GrupoA_StorageController_gRPCService_FileSystem_DirContents_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return GrupoA.StorageController.gRPCService.FileSystem.FileSystemProto.internal_static_GrupoA_StorageController_gRPCService_FileSystem_DirContents_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            GrupoA.StorageController.gRPCService.FileSystem.DirContents.class, GrupoA.StorageController.gRPCService.FileSystem.DirContents.Builder.class);
  }

  public interface ContentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.GrupoA.StorageController.gRPCService.FileSystem.FileType ContentFileType = 1;</code>
     */
    int getContentFileTypeValue();
    /**
     * <code>.GrupoA.StorageController.gRPCService.FileSystem.FileType ContentFileType = 1;</code>
     */
    GrupoA.StorageController.gRPCService.FileSystem.FileType getContentFileType();

    /**
     * <code>string ContentName = 2;</code>
     */
    java.lang.String getContentName();
    /**
     * <code>string ContentName = 2;</code>
     */
    com.google.protobuf.ByteString
        getContentNameBytes();

    /**
     * <code>int64 iNode = 3;</code>
     */
    long getINode();
  }
  /**
   * Protobuf type {@code GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content}
   */
  public  static final class Content extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content)
      ContentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Content.newBuilder() to construct.
    private Content(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Content() {
      contentFileType_ = 0;
      contentName_ = "";
      iNode_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Content(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              contentFileType_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              contentName_ = s;
              break;
            }
            case 24: {

              iNode_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GrupoA.StorageController.gRPCService.FileSystem.FileSystemProto.internal_static_GrupoA_StorageController_gRPCService_FileSystem_DirContents_Content_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GrupoA.StorageController.gRPCService.FileSystem.FileSystemProto.internal_static_GrupoA_StorageController_gRPCService_FileSystem_DirContents_Content_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content.class, GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content.Builder.class);
    }

    public static final int CONTENTFILETYPE_FIELD_NUMBER = 1;
    private int contentFileType_;
    /**
     * <code>.GrupoA.StorageController.gRPCService.FileSystem.FileType ContentFileType = 1;</code>
     */
    public int getContentFileTypeValue() {
      return contentFileType_;
    }
    /**
     * <code>.GrupoA.StorageController.gRPCService.FileSystem.FileType ContentFileType = 1;</code>
     */
    public GrupoA.StorageController.gRPCService.FileSystem.FileType getContentFileType() {
      @SuppressWarnings("deprecation")
      GrupoA.StorageController.gRPCService.FileSystem.FileType result = GrupoA.StorageController.gRPCService.FileSystem.FileType.valueOf(contentFileType_);
      return result == null ? GrupoA.StorageController.gRPCService.FileSystem.FileType.UNRECOGNIZED : result;
    }

    public static final int CONTENTNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object contentName_;
    /**
     * <code>string ContentName = 2;</code>
     */
    public java.lang.String getContentName() {
      java.lang.Object ref = contentName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contentName_ = s;
        return s;
      }
    }
    /**
     * <code>string ContentName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getContentNameBytes() {
      java.lang.Object ref = contentName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contentName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INODE_FIELD_NUMBER = 3;
    private long iNode_;
    /**
     * <code>int64 iNode = 3;</code>
     */
    public long getINode() {
      return iNode_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (contentFileType_ != GrupoA.StorageController.gRPCService.FileSystem.FileType.DIR.getNumber()) {
        output.writeEnum(1, contentFileType_);
      }
      if (!getContentNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, contentName_);
      }
      if (iNode_ != 0L) {
        output.writeInt64(3, iNode_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (contentFileType_ != GrupoA.StorageController.gRPCService.FileSystem.FileType.DIR.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, contentFileType_);
      }
      if (!getContentNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, contentName_);
      }
      if (iNode_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, iNode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content)) {
        return super.equals(obj);
      }
      GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content other = (GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content) obj;

      boolean result = true;
      result = result && contentFileType_ == other.contentFileType_;
      result = result && getContentName()
          .equals(other.getContentName());
      result = result && (getINode()
          == other.getINode());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CONTENTFILETYPE_FIELD_NUMBER;
      hash = (53 * hash) + contentFileType_;
      hash = (37 * hash) + CONTENTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getContentName().hashCode();
      hash = (37 * hash) + INODE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getINode());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content)
        GrupoA.StorageController.gRPCService.FileSystem.DirContents.ContentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GrupoA.StorageController.gRPCService.FileSystem.FileSystemProto.internal_static_GrupoA_StorageController_gRPCService_FileSystem_DirContents_Content_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GrupoA.StorageController.gRPCService.FileSystem.FileSystemProto.internal_static_GrupoA_StorageController_gRPCService_FileSystem_DirContents_Content_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content.class, GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content.Builder.class);
      }

      // Construct using GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        contentFileType_ = 0;

        contentName_ = "";

        iNode_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GrupoA.StorageController.gRPCService.FileSystem.FileSystemProto.internal_static_GrupoA_StorageController_gRPCService_FileSystem_DirContents_Content_descriptor;
      }

      @java.lang.Override
      public GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content getDefaultInstanceForType() {
        return GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content.getDefaultInstance();
      }

      @java.lang.Override
      public GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content build() {
        GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content buildPartial() {
        GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content result = new GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content(this);
        result.contentFileType_ = contentFileType_;
        result.contentName_ = contentName_;
        result.iNode_ = iNode_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content) {
          return mergeFrom((GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content other) {
        if (other == GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content.getDefaultInstance()) return this;
        if (other.contentFileType_ != 0) {
          setContentFileTypeValue(other.getContentFileTypeValue());
        }
        if (!other.getContentName().isEmpty()) {
          contentName_ = other.contentName_;
          onChanged();
        }
        if (other.getINode() != 0L) {
          setINode(other.getINode());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int contentFileType_ = 0;
      /**
       * <code>.GrupoA.StorageController.gRPCService.FileSystem.FileType ContentFileType = 1;</code>
       */
      public int getContentFileTypeValue() {
        return contentFileType_;
      }
      /**
       * <code>.GrupoA.StorageController.gRPCService.FileSystem.FileType ContentFileType = 1;</code>
       */
      public Builder setContentFileTypeValue(int value) {
        contentFileType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.GrupoA.StorageController.gRPCService.FileSystem.FileType ContentFileType = 1;</code>
       */
      public GrupoA.StorageController.gRPCService.FileSystem.FileType getContentFileType() {
        @SuppressWarnings("deprecation")
        GrupoA.StorageController.gRPCService.FileSystem.FileType result = GrupoA.StorageController.gRPCService.FileSystem.FileType.valueOf(contentFileType_);
        return result == null ? GrupoA.StorageController.gRPCService.FileSystem.FileType.UNRECOGNIZED : result;
      }
      /**
       * <code>.GrupoA.StorageController.gRPCService.FileSystem.FileType ContentFileType = 1;</code>
       */
      public Builder setContentFileType(GrupoA.StorageController.gRPCService.FileSystem.FileType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        contentFileType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.GrupoA.StorageController.gRPCService.FileSystem.FileType ContentFileType = 1;</code>
       */
      public Builder clearContentFileType() {
        
        contentFileType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object contentName_ = "";
      /**
       * <code>string ContentName = 2;</code>
       */
      public java.lang.String getContentName() {
        java.lang.Object ref = contentName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          contentName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ContentName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getContentNameBytes() {
        java.lang.Object ref = contentName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          contentName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ContentName = 2;</code>
       */
      public Builder setContentName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        contentName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ContentName = 2;</code>
       */
      public Builder clearContentName() {
        
        contentName_ = getDefaultInstance().getContentName();
        onChanged();
        return this;
      }
      /**
       * <code>string ContentName = 2;</code>
       */
      public Builder setContentNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        contentName_ = value;
        onChanged();
        return this;
      }

      private long iNode_ ;
      /**
       * <code>int64 iNode = 3;</code>
       */
      public long getINode() {
        return iNode_;
      }
      /**
       * <code>int64 iNode = 3;</code>
       */
      public Builder setINode(long value) {
        
        iNode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 iNode = 3;</code>
       */
      public Builder clearINode() {
        
        iNode_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content)
    }

    // @@protoc_insertion_point(class_scope:GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content)
    private static final GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content();
    }

    public static GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Content>
        PARSER = new com.google.protobuf.AbstractParser<Content>() {
      @java.lang.Override
      public Content parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Content(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Content> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Content> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int SUCCESS_FIELD_NUMBER = 1;
  private boolean success_;
  /**
   * <code>bool success = 1;</code>
   */
  public boolean getSuccess() {
    return success_;
  }

  public static final int PARENTINODE_FIELD_NUMBER = 2;
  private long parentINode_;
  /**
   * <code>int64 parentINode = 2;</code>
   */
  public long getParentINode() {
    return parentINode_;
  }

  public static final int INODE_FIELD_NUMBER = 3;
  private long iNode_;
  /**
   * <code>int64 INode = 3;</code>
   */
  public long getINode() {
    return iNode_;
  }

  public static final int CONTENTS_FIELD_NUMBER = 4;
  private java.util.List<GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content> contents_;
  /**
   * <code>repeated .GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content Contents = 4;</code>
   */
  public java.util.List<GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content> getContentsList() {
    return contents_;
  }
  /**
   * <code>repeated .GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content Contents = 4;</code>
   */
  public java.util.List<? extends GrupoA.StorageController.gRPCService.FileSystem.DirContents.ContentOrBuilder> 
      getContentsOrBuilderList() {
    return contents_;
  }
  /**
   * <code>repeated .GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content Contents = 4;</code>
   */
  public int getContentsCount() {
    return contents_.size();
  }
  /**
   * <code>repeated .GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content Contents = 4;</code>
   */
  public GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content getContents(int index) {
    return contents_.get(index);
  }
  /**
   * <code>repeated .GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content Contents = 4;</code>
   */
  public GrupoA.StorageController.gRPCService.FileSystem.DirContents.ContentOrBuilder getContentsOrBuilder(
      int index) {
    return contents_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (success_ != false) {
      output.writeBool(1, success_);
    }
    if (parentINode_ != 0L) {
      output.writeInt64(2, parentINode_);
    }
    if (iNode_ != 0L) {
      output.writeInt64(3, iNode_);
    }
    for (int i = 0; i < contents_.size(); i++) {
      output.writeMessage(4, contents_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (success_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, success_);
    }
    if (parentINode_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, parentINode_);
    }
    if (iNode_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, iNode_);
    }
    for (int i = 0; i < contents_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, contents_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof GrupoA.StorageController.gRPCService.FileSystem.DirContents)) {
      return super.equals(obj);
    }
    GrupoA.StorageController.gRPCService.FileSystem.DirContents other = (GrupoA.StorageController.gRPCService.FileSystem.DirContents) obj;

    boolean result = true;
    result = result && (getSuccess()
        == other.getSuccess());
    result = result && (getParentINode()
        == other.getParentINode());
    result = result && (getINode()
        == other.getINode());
    result = result && getContentsList()
        .equals(other.getContentsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSuccess());
    hash = (37 * hash) + PARENTINODE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getParentINode());
    hash = (37 * hash) + INODE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getINode());
    if (getContentsCount() > 0) {
      hash = (37 * hash) + CONTENTS_FIELD_NUMBER;
      hash = (53 * hash) + getContentsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static GrupoA.StorageController.gRPCService.FileSystem.DirContents parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GrupoA.StorageController.gRPCService.FileSystem.DirContents parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GrupoA.StorageController.gRPCService.FileSystem.DirContents parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GrupoA.StorageController.gRPCService.FileSystem.DirContents parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GrupoA.StorageController.gRPCService.FileSystem.DirContents parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GrupoA.StorageController.gRPCService.FileSystem.DirContents parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GrupoA.StorageController.gRPCService.FileSystem.DirContents parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static GrupoA.StorageController.gRPCService.FileSystem.DirContents parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static GrupoA.StorageController.gRPCService.FileSystem.DirContents parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static GrupoA.StorageController.gRPCService.FileSystem.DirContents parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static GrupoA.StorageController.gRPCService.FileSystem.DirContents parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static GrupoA.StorageController.gRPCService.FileSystem.DirContents parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(GrupoA.StorageController.gRPCService.FileSystem.DirContents prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GrupoA.StorageController.gRPCService.FileSystem.DirContents}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GrupoA.StorageController.gRPCService.FileSystem.DirContents)
      GrupoA.StorageController.gRPCService.FileSystem.DirContentsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GrupoA.StorageController.gRPCService.FileSystem.FileSystemProto.internal_static_GrupoA_StorageController_gRPCService_FileSystem_DirContents_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GrupoA.StorageController.gRPCService.FileSystem.FileSystemProto.internal_static_GrupoA_StorageController_gRPCService_FileSystem_DirContents_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GrupoA.StorageController.gRPCService.FileSystem.DirContents.class, GrupoA.StorageController.gRPCService.FileSystem.DirContents.Builder.class);
    }

    // Construct using GrupoA.StorageController.gRPCService.FileSystem.DirContents.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getContentsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      success_ = false;

      parentINode_ = 0L;

      iNode_ = 0L;

      if (contentsBuilder_ == null) {
        contents_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        contentsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return GrupoA.StorageController.gRPCService.FileSystem.FileSystemProto.internal_static_GrupoA_StorageController_gRPCService_FileSystem_DirContents_descriptor;
    }

    @java.lang.Override
    public GrupoA.StorageController.gRPCService.FileSystem.DirContents getDefaultInstanceForType() {
      return GrupoA.StorageController.gRPCService.FileSystem.DirContents.getDefaultInstance();
    }

    @java.lang.Override
    public GrupoA.StorageController.gRPCService.FileSystem.DirContents build() {
      GrupoA.StorageController.gRPCService.FileSystem.DirContents result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public GrupoA.StorageController.gRPCService.FileSystem.DirContents buildPartial() {
      GrupoA.StorageController.gRPCService.FileSystem.DirContents result = new GrupoA.StorageController.gRPCService.FileSystem.DirContents(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.success_ = success_;
      result.parentINode_ = parentINode_;
      result.iNode_ = iNode_;
      if (contentsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          contents_ = java.util.Collections.unmodifiableList(contents_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.contents_ = contents_;
      } else {
        result.contents_ = contentsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof GrupoA.StorageController.gRPCService.FileSystem.DirContents) {
        return mergeFrom((GrupoA.StorageController.gRPCService.FileSystem.DirContents)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(GrupoA.StorageController.gRPCService.FileSystem.DirContents other) {
      if (other == GrupoA.StorageController.gRPCService.FileSystem.DirContents.getDefaultInstance()) return this;
      if (other.getSuccess() != false) {
        setSuccess(other.getSuccess());
      }
      if (other.getParentINode() != 0L) {
        setParentINode(other.getParentINode());
      }
      if (other.getINode() != 0L) {
        setINode(other.getINode());
      }
      if (contentsBuilder_ == null) {
        if (!other.contents_.isEmpty()) {
          if (contents_.isEmpty()) {
            contents_ = other.contents_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureContentsIsMutable();
            contents_.addAll(other.contents_);
          }
          onChanged();
        }
      } else {
        if (!other.contents_.isEmpty()) {
          if (contentsBuilder_.isEmpty()) {
            contentsBuilder_.dispose();
            contentsBuilder_ = null;
            contents_ = other.contents_;
            bitField0_ = (bitField0_ & ~0x00000008);
            contentsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getContentsFieldBuilder() : null;
          } else {
            contentsBuilder_.addAllMessages(other.contents_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      GrupoA.StorageController.gRPCService.FileSystem.DirContents parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (GrupoA.StorageController.gRPCService.FileSystem.DirContents) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private boolean success_ ;
    /**
     * <code>bool success = 1;</code>
     */
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <code>bool success = 1;</code>
     */
    public Builder setSuccess(boolean value) {
      
      success_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool success = 1;</code>
     */
    public Builder clearSuccess() {
      
      success_ = false;
      onChanged();
      return this;
    }

    private long parentINode_ ;
    /**
     * <code>int64 parentINode = 2;</code>
     */
    public long getParentINode() {
      return parentINode_;
    }
    /**
     * <code>int64 parentINode = 2;</code>
     */
    public Builder setParentINode(long value) {
      
      parentINode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 parentINode = 2;</code>
     */
    public Builder clearParentINode() {
      
      parentINode_ = 0L;
      onChanged();
      return this;
    }

    private long iNode_ ;
    /**
     * <code>int64 INode = 3;</code>
     */
    public long getINode() {
      return iNode_;
    }
    /**
     * <code>int64 INode = 3;</code>
     */
    public Builder setINode(long value) {
      
      iNode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 INode = 3;</code>
     */
    public Builder clearINode() {
      
      iNode_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content> contents_ =
      java.util.Collections.emptyList();
    private void ensureContentsIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        contents_ = new java.util.ArrayList<GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content>(contents_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content, GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content.Builder, GrupoA.StorageController.gRPCService.FileSystem.DirContents.ContentOrBuilder> contentsBuilder_;

    /**
     * <code>repeated .GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content Contents = 4;</code>
     */
    public java.util.List<GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content> getContentsList() {
      if (contentsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(contents_);
      } else {
        return contentsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content Contents = 4;</code>
     */
    public int getContentsCount() {
      if (contentsBuilder_ == null) {
        return contents_.size();
      } else {
        return contentsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content Contents = 4;</code>
     */
    public GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content getContents(int index) {
      if (contentsBuilder_ == null) {
        return contents_.get(index);
      } else {
        return contentsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content Contents = 4;</code>
     */
    public Builder setContents(
        int index, GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content value) {
      if (contentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureContentsIsMutable();
        contents_.set(index, value);
        onChanged();
      } else {
        contentsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content Contents = 4;</code>
     */
    public Builder setContents(
        int index, GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content.Builder builderForValue) {
      if (contentsBuilder_ == null) {
        ensureContentsIsMutable();
        contents_.set(index, builderForValue.build());
        onChanged();
      } else {
        contentsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content Contents = 4;</code>
     */
    public Builder addContents(GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content value) {
      if (contentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureContentsIsMutable();
        contents_.add(value);
        onChanged();
      } else {
        contentsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content Contents = 4;</code>
     */
    public Builder addContents(
        int index, GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content value) {
      if (contentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureContentsIsMutable();
        contents_.add(index, value);
        onChanged();
      } else {
        contentsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content Contents = 4;</code>
     */
    public Builder addContents(
        GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content.Builder builderForValue) {
      if (contentsBuilder_ == null) {
        ensureContentsIsMutable();
        contents_.add(builderForValue.build());
        onChanged();
      } else {
        contentsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content Contents = 4;</code>
     */
    public Builder addContents(
        int index, GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content.Builder builderForValue) {
      if (contentsBuilder_ == null) {
        ensureContentsIsMutable();
        contents_.add(index, builderForValue.build());
        onChanged();
      } else {
        contentsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content Contents = 4;</code>
     */
    public Builder addAllContents(
        java.lang.Iterable<? extends GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content> values) {
      if (contentsBuilder_ == null) {
        ensureContentsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, contents_);
        onChanged();
      } else {
        contentsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content Contents = 4;</code>
     */
    public Builder clearContents() {
      if (contentsBuilder_ == null) {
        contents_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        contentsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content Contents = 4;</code>
     */
    public Builder removeContents(int index) {
      if (contentsBuilder_ == null) {
        ensureContentsIsMutable();
        contents_.remove(index);
        onChanged();
      } else {
        contentsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content Contents = 4;</code>
     */
    public GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content.Builder getContentsBuilder(
        int index) {
      return getContentsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content Contents = 4;</code>
     */
    public GrupoA.StorageController.gRPCService.FileSystem.DirContents.ContentOrBuilder getContentsOrBuilder(
        int index) {
      if (contentsBuilder_ == null) {
        return contents_.get(index);  } else {
        return contentsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content Contents = 4;</code>
     */
    public java.util.List<? extends GrupoA.StorageController.gRPCService.FileSystem.DirContents.ContentOrBuilder> 
         getContentsOrBuilderList() {
      if (contentsBuilder_ != null) {
        return contentsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(contents_);
      }
    }
    /**
     * <code>repeated .GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content Contents = 4;</code>
     */
    public GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content.Builder addContentsBuilder() {
      return getContentsFieldBuilder().addBuilder(
          GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content.getDefaultInstance());
    }
    /**
     * <code>repeated .GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content Contents = 4;</code>
     */
    public GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content.Builder addContentsBuilder(
        int index) {
      return getContentsFieldBuilder().addBuilder(
          index, GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content.getDefaultInstance());
    }
    /**
     * <code>repeated .GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content Contents = 4;</code>
     */
    public java.util.List<GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content.Builder> 
         getContentsBuilderList() {
      return getContentsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content, GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content.Builder, GrupoA.StorageController.gRPCService.FileSystem.DirContents.ContentOrBuilder> 
        getContentsFieldBuilder() {
      if (contentsBuilder_ == null) {
        contentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content, GrupoA.StorageController.gRPCService.FileSystem.DirContents.Content.Builder, GrupoA.StorageController.gRPCService.FileSystem.DirContents.ContentOrBuilder>(
                contents_,
                ((bitField0_ & 0x00000008) == 0x00000008),
                getParentForChildren(),
                isClean());
        contents_ = null;
      }
      return contentsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GrupoA.StorageController.gRPCService.FileSystem.DirContents)
  }

  // @@protoc_insertion_point(class_scope:GrupoA.StorageController.gRPCService.FileSystem.DirContents)
  private static final GrupoA.StorageController.gRPCService.FileSystem.DirContents DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new GrupoA.StorageController.gRPCService.FileSystem.DirContents();
  }

  public static GrupoA.StorageController.gRPCService.FileSystem.DirContents getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DirContents>
      PARSER = new com.google.protobuf.AbstractParser<DirContents>() {
    @java.lang.Override
    public DirContents parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DirContents(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DirContents> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DirContents> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public GrupoA.StorageController.gRPCService.FileSystem.DirContents getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

