// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FileSystem.proto

package GrupoA.StorageController.gRPCService.FileSystem;

/**
 * Protobuf enum {@code GrupoA.StorageController.gRPCService.FileSystem.FileType}
 */
public enum FileType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>DIR = 0;</code>
   */
  DIR(0),
  /**
   * <code>FILE = 1;</code>
   */
  FILE(1),
  /**
   * <code>LINK = 2;</code>
   */
  LINK(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>DIR = 0;</code>
   */
  public static final int DIR_VALUE = 0;
  /**
   * <code>FILE = 1;</code>
   */
  public static final int FILE_VALUE = 1;
  /**
   * <code>LINK = 2;</code>
   */
  public static final int LINK_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static FileType valueOf(int value) {
    return forNumber(value);
  }

  public static FileType forNumber(int value) {
    switch (value) {
      case 0: return DIR;
      case 1: return FILE;
      case 2: return LINK;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<FileType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      FileType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<FileType>() {
          public FileType findValueByNumber(int number) {
            return FileType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return GrupoA.StorageController.gRPCService.FileSystem.FileSystemProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final FileType[] VALUES = values();

  public static FileType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private FileType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:GrupoA.StorageController.gRPCService.FileSystem.FileType)
}

