// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FileSystem.proto

package GrupoA.StorageController.gRPCService.FileSystem;

/**
 * Protobuf type {@code GrupoA.StorageController.gRPCService.FileSystem.iNodeAttributes}
 */
public  final class iNodeAttributes extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GrupoA.StorageController.gRPCService.FileSystem.iNodeAttributes)
    iNodeAttributesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use iNodeAttributes.newBuilder() to construct.
  private iNodeAttributes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private iNodeAttributes() {
    name_ = "";
    fileType_ = 0;
    userPermissions_ = 0;
    groupPermissions_ = 0;
    otherPermissions_ = 0;
    ownerId_ = 0L;
    groupId_ = 0L;
    iNodeNumber_ = 0L;
    parentINodeNumber_ = 0L;
    size_ = 0L;
    ctime_ = 0L;
    atime_ = 0L;
    mtime_ = 0L;
    redundancy_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private iNodeAttributes(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 16: {

            userPermissions_ = input.readInt32();
            break;
          }
          case 24: {

            groupPermissions_ = input.readInt32();
            break;
          }
          case 32: {

            otherPermissions_ = input.readInt32();
            break;
          }
          case 40: {

            ownerId_ = input.readInt64();
            break;
          }
          case 48: {

            groupId_ = input.readInt64();
            break;
          }
          case 56: {

            iNodeNumber_ = input.readInt64();
            break;
          }
          case 64: {

            parentINodeNumber_ = input.readInt64();
            break;
          }
          case 72: {

            size_ = input.readInt64();
            break;
          }
          case 80: {
            int rawValue = input.readEnum();

            fileType_ = rawValue;
            break;
          }
          case 88: {

            ctime_ = input.readInt64();
            break;
          }
          case 96: {

            atime_ = input.readInt64();
            break;
          }
          case 104: {

            mtime_ = input.readInt64();
            break;
          }
          case 112: {
            int rawValue = input.readEnum();

            redundancy_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return GrupoA.StorageController.gRPCService.FileSystem.FileSystemProto.internal_static_GrupoA_StorageController_gRPCService_FileSystem_iNodeAttributes_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return GrupoA.StorageController.gRPCService.FileSystem.FileSystemProto.internal_static_GrupoA_StorageController_gRPCService_FileSystem_iNodeAttributes_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            GrupoA.StorageController.gRPCService.FileSystem.iNodeAttributes.class, GrupoA.StorageController.gRPCService.FileSystem.iNodeAttributes.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 1;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILETYPE_FIELD_NUMBER = 10;
  private int fileType_;
  /**
   * <code>.GrupoA.StorageController.gRPCService.FileSystem.FileType FileType = 10;</code>
   */
  public int getFileTypeValue() {
    return fileType_;
  }
  /**
   * <code>.GrupoA.StorageController.gRPCService.FileSystem.FileType FileType = 10;</code>
   */
  public GrupoA.StorageController.gRPCService.FileSystem.FileType getFileType() {
    @SuppressWarnings("deprecation")
    GrupoA.StorageController.gRPCService.FileSystem.FileType result = GrupoA.StorageController.gRPCService.FileSystem.FileType.valueOf(fileType_);
    return result == null ? GrupoA.StorageController.gRPCService.FileSystem.FileType.UNRECOGNIZED : result;
  }

  public static final int USERPERMISSIONS_FIELD_NUMBER = 2;
  private int userPermissions_;
  /**
   * <code>int32 UserPermissions = 2;</code>
   */
  public int getUserPermissions() {
    return userPermissions_;
  }

  public static final int GROUPPERMISSIONS_FIELD_NUMBER = 3;
  private int groupPermissions_;
  /**
   * <code>int32 GroupPermissions = 3;</code>
   */
  public int getGroupPermissions() {
    return groupPermissions_;
  }

  public static final int OTHERPERMISSIONS_FIELD_NUMBER = 4;
  private int otherPermissions_;
  /**
   * <code>int32 OtherPermissions = 4;</code>
   */
  public int getOtherPermissions() {
    return otherPermissions_;
  }

  public static final int OWNERID_FIELD_NUMBER = 5;
  private long ownerId_;
  /**
   * <code>int64 OwnerId = 5;</code>
   */
  public long getOwnerId() {
    return ownerId_;
  }

  public static final int GROUPID_FIELD_NUMBER = 6;
  private long groupId_;
  /**
   * <code>int64 GroupId = 6;</code>
   */
  public long getGroupId() {
    return groupId_;
  }

  public static final int INODENUMBER_FIELD_NUMBER = 7;
  private long iNodeNumber_;
  /**
   * <code>int64 INodeNumber = 7;</code>
   */
  public long getINodeNumber() {
    return iNodeNumber_;
  }

  public static final int PARENTINODENUMBER_FIELD_NUMBER = 8;
  private long parentINodeNumber_;
  /**
   * <code>int64 ParentINodeNumber = 8;</code>
   */
  public long getParentINodeNumber() {
    return parentINodeNumber_;
  }

  public static final int SIZE_FIELD_NUMBER = 9;
  private long size_;
  /**
   * <code>int64 Size = 9;</code>
   */
  public long getSize() {
    return size_;
  }

  public static final int CTIME_FIELD_NUMBER = 11;
  private long ctime_;
  /**
   * <code>int64 ctime = 11;</code>
   */
  public long getCtime() {
    return ctime_;
  }

  public static final int ATIME_FIELD_NUMBER = 12;
  private long atime_;
  /**
   * <code>int64 atime = 12;</code>
   */
  public long getAtime() {
    return atime_;
  }

  public static final int MTIME_FIELD_NUMBER = 13;
  private long mtime_;
  /**
   * <code>int64 mtime = 13;</code>
   */
  public long getMtime() {
    return mtime_;
  }

  public static final int REDUNDANCY_FIELD_NUMBER = 14;
  private int redundancy_;
  /**
   * <code>.GrupoA.StorageController.gRPCService.FileSystem.RedundancyProto Redundancy = 14;</code>
   */
  public int getRedundancyValue() {
    return redundancy_;
  }
  /**
   * <code>.GrupoA.StorageController.gRPCService.FileSystem.RedundancyProto Redundancy = 14;</code>
   */
  public GrupoA.StorageController.gRPCService.FileSystem.RedundancyProto getRedundancy() {
    @SuppressWarnings("deprecation")
    GrupoA.StorageController.gRPCService.FileSystem.RedundancyProto result = GrupoA.StorageController.gRPCService.FileSystem.RedundancyProto.valueOf(redundancy_);
    return result == null ? GrupoA.StorageController.gRPCService.FileSystem.RedundancyProto.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (userPermissions_ != 0) {
      output.writeInt32(2, userPermissions_);
    }
    if (groupPermissions_ != 0) {
      output.writeInt32(3, groupPermissions_);
    }
    if (otherPermissions_ != 0) {
      output.writeInt32(4, otherPermissions_);
    }
    if (ownerId_ != 0L) {
      output.writeInt64(5, ownerId_);
    }
    if (groupId_ != 0L) {
      output.writeInt64(6, groupId_);
    }
    if (iNodeNumber_ != 0L) {
      output.writeInt64(7, iNodeNumber_);
    }
    if (parentINodeNumber_ != 0L) {
      output.writeInt64(8, parentINodeNumber_);
    }
    if (size_ != 0L) {
      output.writeInt64(9, size_);
    }
    if (fileType_ != GrupoA.StorageController.gRPCService.FileSystem.FileType.DIR.getNumber()) {
      output.writeEnum(10, fileType_);
    }
    if (ctime_ != 0L) {
      output.writeInt64(11, ctime_);
    }
    if (atime_ != 0L) {
      output.writeInt64(12, atime_);
    }
    if (mtime_ != 0L) {
      output.writeInt64(13, mtime_);
    }
    if (redundancy_ != GrupoA.StorageController.gRPCService.FileSystem.RedundancyProto.ForwardErrorCorrection.getNumber()) {
      output.writeEnum(14, redundancy_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (userPermissions_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, userPermissions_);
    }
    if (groupPermissions_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, groupPermissions_);
    }
    if (otherPermissions_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, otherPermissions_);
    }
    if (ownerId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, ownerId_);
    }
    if (groupId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, groupId_);
    }
    if (iNodeNumber_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, iNodeNumber_);
    }
    if (parentINodeNumber_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, parentINodeNumber_);
    }
    if (size_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, size_);
    }
    if (fileType_ != GrupoA.StorageController.gRPCService.FileSystem.FileType.DIR.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(10, fileType_);
    }
    if (ctime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(11, ctime_);
    }
    if (atime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(12, atime_);
    }
    if (mtime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(13, mtime_);
    }
    if (redundancy_ != GrupoA.StorageController.gRPCService.FileSystem.RedundancyProto.ForwardErrorCorrection.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(14, redundancy_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof GrupoA.StorageController.gRPCService.FileSystem.iNodeAttributes)) {
      return super.equals(obj);
    }
    GrupoA.StorageController.gRPCService.FileSystem.iNodeAttributes other = (GrupoA.StorageController.gRPCService.FileSystem.iNodeAttributes) obj;

    boolean result = true;
    result = result && getName()
        .equals(other.getName());
    result = result && fileType_ == other.fileType_;
    result = result && (getUserPermissions()
        == other.getUserPermissions());
    result = result && (getGroupPermissions()
        == other.getGroupPermissions());
    result = result && (getOtherPermissions()
        == other.getOtherPermissions());
    result = result && (getOwnerId()
        == other.getOwnerId());
    result = result && (getGroupId()
        == other.getGroupId());
    result = result && (getINodeNumber()
        == other.getINodeNumber());
    result = result && (getParentINodeNumber()
        == other.getParentINodeNumber());
    result = result && (getSize()
        == other.getSize());
    result = result && (getCtime()
        == other.getCtime());
    result = result && (getAtime()
        == other.getAtime());
    result = result && (getMtime()
        == other.getMtime());
    result = result && redundancy_ == other.redundancy_;
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + FILETYPE_FIELD_NUMBER;
    hash = (53 * hash) + fileType_;
    hash = (37 * hash) + USERPERMISSIONS_FIELD_NUMBER;
    hash = (53 * hash) + getUserPermissions();
    hash = (37 * hash) + GROUPPERMISSIONS_FIELD_NUMBER;
    hash = (53 * hash) + getGroupPermissions();
    hash = (37 * hash) + OTHERPERMISSIONS_FIELD_NUMBER;
    hash = (53 * hash) + getOtherPermissions();
    hash = (37 * hash) + OWNERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getOwnerId());
    hash = (37 * hash) + GROUPID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getGroupId());
    hash = (37 * hash) + INODENUMBER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getINodeNumber());
    hash = (37 * hash) + PARENTINODENUMBER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getParentINodeNumber());
    hash = (37 * hash) + SIZE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSize());
    hash = (37 * hash) + CTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCtime());
    hash = (37 * hash) + ATIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAtime());
    hash = (37 * hash) + MTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMtime());
    hash = (37 * hash) + REDUNDANCY_FIELD_NUMBER;
    hash = (53 * hash) + redundancy_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static GrupoA.StorageController.gRPCService.FileSystem.iNodeAttributes parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GrupoA.StorageController.gRPCService.FileSystem.iNodeAttributes parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GrupoA.StorageController.gRPCService.FileSystem.iNodeAttributes parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GrupoA.StorageController.gRPCService.FileSystem.iNodeAttributes parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GrupoA.StorageController.gRPCService.FileSystem.iNodeAttributes parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GrupoA.StorageController.gRPCService.FileSystem.iNodeAttributes parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GrupoA.StorageController.gRPCService.FileSystem.iNodeAttributes parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static GrupoA.StorageController.gRPCService.FileSystem.iNodeAttributes parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static GrupoA.StorageController.gRPCService.FileSystem.iNodeAttributes parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static GrupoA.StorageController.gRPCService.FileSystem.iNodeAttributes parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static GrupoA.StorageController.gRPCService.FileSystem.iNodeAttributes parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static GrupoA.StorageController.gRPCService.FileSystem.iNodeAttributes parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(GrupoA.StorageController.gRPCService.FileSystem.iNodeAttributes prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GrupoA.StorageController.gRPCService.FileSystem.iNodeAttributes}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GrupoA.StorageController.gRPCService.FileSystem.iNodeAttributes)
      GrupoA.StorageController.gRPCService.FileSystem.iNodeAttributesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GrupoA.StorageController.gRPCService.FileSystem.FileSystemProto.internal_static_GrupoA_StorageController_gRPCService_FileSystem_iNodeAttributes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GrupoA.StorageController.gRPCService.FileSystem.FileSystemProto.internal_static_GrupoA_StorageController_gRPCService_FileSystem_iNodeAttributes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GrupoA.StorageController.gRPCService.FileSystem.iNodeAttributes.class, GrupoA.StorageController.gRPCService.FileSystem.iNodeAttributes.Builder.class);
    }

    // Construct using GrupoA.StorageController.gRPCService.FileSystem.iNodeAttributes.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";

      fileType_ = 0;

      userPermissions_ = 0;

      groupPermissions_ = 0;

      otherPermissions_ = 0;

      ownerId_ = 0L;

      groupId_ = 0L;

      iNodeNumber_ = 0L;

      parentINodeNumber_ = 0L;

      size_ = 0L;

      ctime_ = 0L;

      atime_ = 0L;

      mtime_ = 0L;

      redundancy_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return GrupoA.StorageController.gRPCService.FileSystem.FileSystemProto.internal_static_GrupoA_StorageController_gRPCService_FileSystem_iNodeAttributes_descriptor;
    }

    @java.lang.Override
    public GrupoA.StorageController.gRPCService.FileSystem.iNodeAttributes getDefaultInstanceForType() {
      return GrupoA.StorageController.gRPCService.FileSystem.iNodeAttributes.getDefaultInstance();
    }

    @java.lang.Override
    public GrupoA.StorageController.gRPCService.FileSystem.iNodeAttributes build() {
      GrupoA.StorageController.gRPCService.FileSystem.iNodeAttributes result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public GrupoA.StorageController.gRPCService.FileSystem.iNodeAttributes buildPartial() {
      GrupoA.StorageController.gRPCService.FileSystem.iNodeAttributes result = new GrupoA.StorageController.gRPCService.FileSystem.iNodeAttributes(this);
      result.name_ = name_;
      result.fileType_ = fileType_;
      result.userPermissions_ = userPermissions_;
      result.groupPermissions_ = groupPermissions_;
      result.otherPermissions_ = otherPermissions_;
      result.ownerId_ = ownerId_;
      result.groupId_ = groupId_;
      result.iNodeNumber_ = iNodeNumber_;
      result.parentINodeNumber_ = parentINodeNumber_;
      result.size_ = size_;
      result.ctime_ = ctime_;
      result.atime_ = atime_;
      result.mtime_ = mtime_;
      result.redundancy_ = redundancy_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof GrupoA.StorageController.gRPCService.FileSystem.iNodeAttributes) {
        return mergeFrom((GrupoA.StorageController.gRPCService.FileSystem.iNodeAttributes)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(GrupoA.StorageController.gRPCService.FileSystem.iNodeAttributes other) {
      if (other == GrupoA.StorageController.gRPCService.FileSystem.iNodeAttributes.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.fileType_ != 0) {
        setFileTypeValue(other.getFileTypeValue());
      }
      if (other.getUserPermissions() != 0) {
        setUserPermissions(other.getUserPermissions());
      }
      if (other.getGroupPermissions() != 0) {
        setGroupPermissions(other.getGroupPermissions());
      }
      if (other.getOtherPermissions() != 0) {
        setOtherPermissions(other.getOtherPermissions());
      }
      if (other.getOwnerId() != 0L) {
        setOwnerId(other.getOwnerId());
      }
      if (other.getGroupId() != 0L) {
        setGroupId(other.getGroupId());
      }
      if (other.getINodeNumber() != 0L) {
        setINodeNumber(other.getINodeNumber());
      }
      if (other.getParentINodeNumber() != 0L) {
        setParentINodeNumber(other.getParentINodeNumber());
      }
      if (other.getSize() != 0L) {
        setSize(other.getSize());
      }
      if (other.getCtime() != 0L) {
        setCtime(other.getCtime());
      }
      if (other.getAtime() != 0L) {
        setAtime(other.getAtime());
      }
      if (other.getMtime() != 0L) {
        setMtime(other.getMtime());
      }
      if (other.redundancy_ != 0) {
        setRedundancyValue(other.getRedundancyValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      GrupoA.StorageController.gRPCService.FileSystem.iNodeAttributes parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (GrupoA.StorageController.gRPCService.FileSystem.iNodeAttributes) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private int fileType_ = 0;
    /**
     * <code>.GrupoA.StorageController.gRPCService.FileSystem.FileType FileType = 10;</code>
     */
    public int getFileTypeValue() {
      return fileType_;
    }
    /**
     * <code>.GrupoA.StorageController.gRPCService.FileSystem.FileType FileType = 10;</code>
     */
    public Builder setFileTypeValue(int value) {
      fileType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.GrupoA.StorageController.gRPCService.FileSystem.FileType FileType = 10;</code>
     */
    public GrupoA.StorageController.gRPCService.FileSystem.FileType getFileType() {
      @SuppressWarnings("deprecation")
      GrupoA.StorageController.gRPCService.FileSystem.FileType result = GrupoA.StorageController.gRPCService.FileSystem.FileType.valueOf(fileType_);
      return result == null ? GrupoA.StorageController.gRPCService.FileSystem.FileType.UNRECOGNIZED : result;
    }
    /**
     * <code>.GrupoA.StorageController.gRPCService.FileSystem.FileType FileType = 10;</code>
     */
    public Builder setFileType(GrupoA.StorageController.gRPCService.FileSystem.FileType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      fileType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.GrupoA.StorageController.gRPCService.FileSystem.FileType FileType = 10;</code>
     */
    public Builder clearFileType() {
      
      fileType_ = 0;
      onChanged();
      return this;
    }

    private int userPermissions_ ;
    /**
     * <code>int32 UserPermissions = 2;</code>
     */
    public int getUserPermissions() {
      return userPermissions_;
    }
    /**
     * <code>int32 UserPermissions = 2;</code>
     */
    public Builder setUserPermissions(int value) {
      
      userPermissions_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 UserPermissions = 2;</code>
     */
    public Builder clearUserPermissions() {
      
      userPermissions_ = 0;
      onChanged();
      return this;
    }

    private int groupPermissions_ ;
    /**
     * <code>int32 GroupPermissions = 3;</code>
     */
    public int getGroupPermissions() {
      return groupPermissions_;
    }
    /**
     * <code>int32 GroupPermissions = 3;</code>
     */
    public Builder setGroupPermissions(int value) {
      
      groupPermissions_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 GroupPermissions = 3;</code>
     */
    public Builder clearGroupPermissions() {
      
      groupPermissions_ = 0;
      onChanged();
      return this;
    }

    private int otherPermissions_ ;
    /**
     * <code>int32 OtherPermissions = 4;</code>
     */
    public int getOtherPermissions() {
      return otherPermissions_;
    }
    /**
     * <code>int32 OtherPermissions = 4;</code>
     */
    public Builder setOtherPermissions(int value) {
      
      otherPermissions_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 OtherPermissions = 4;</code>
     */
    public Builder clearOtherPermissions() {
      
      otherPermissions_ = 0;
      onChanged();
      return this;
    }

    private long ownerId_ ;
    /**
     * <code>int64 OwnerId = 5;</code>
     */
    public long getOwnerId() {
      return ownerId_;
    }
    /**
     * <code>int64 OwnerId = 5;</code>
     */
    public Builder setOwnerId(long value) {
      
      ownerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 OwnerId = 5;</code>
     */
    public Builder clearOwnerId() {
      
      ownerId_ = 0L;
      onChanged();
      return this;
    }

    private long groupId_ ;
    /**
     * <code>int64 GroupId = 6;</code>
     */
    public long getGroupId() {
      return groupId_;
    }
    /**
     * <code>int64 GroupId = 6;</code>
     */
    public Builder setGroupId(long value) {
      
      groupId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 GroupId = 6;</code>
     */
    public Builder clearGroupId() {
      
      groupId_ = 0L;
      onChanged();
      return this;
    }

    private long iNodeNumber_ ;
    /**
     * <code>int64 INodeNumber = 7;</code>
     */
    public long getINodeNumber() {
      return iNodeNumber_;
    }
    /**
     * <code>int64 INodeNumber = 7;</code>
     */
    public Builder setINodeNumber(long value) {
      
      iNodeNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 INodeNumber = 7;</code>
     */
    public Builder clearINodeNumber() {
      
      iNodeNumber_ = 0L;
      onChanged();
      return this;
    }

    private long parentINodeNumber_ ;
    /**
     * <code>int64 ParentINodeNumber = 8;</code>
     */
    public long getParentINodeNumber() {
      return parentINodeNumber_;
    }
    /**
     * <code>int64 ParentINodeNumber = 8;</code>
     */
    public Builder setParentINodeNumber(long value) {
      
      parentINodeNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 ParentINodeNumber = 8;</code>
     */
    public Builder clearParentINodeNumber() {
      
      parentINodeNumber_ = 0L;
      onChanged();
      return this;
    }

    private long size_ ;
    /**
     * <code>int64 Size = 9;</code>
     */
    public long getSize() {
      return size_;
    }
    /**
     * <code>int64 Size = 9;</code>
     */
    public Builder setSize(long value) {
      
      size_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 Size = 9;</code>
     */
    public Builder clearSize() {
      
      size_ = 0L;
      onChanged();
      return this;
    }

    private long ctime_ ;
    /**
     * <code>int64 ctime = 11;</code>
     */
    public long getCtime() {
      return ctime_;
    }
    /**
     * <code>int64 ctime = 11;</code>
     */
    public Builder setCtime(long value) {
      
      ctime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 ctime = 11;</code>
     */
    public Builder clearCtime() {
      
      ctime_ = 0L;
      onChanged();
      return this;
    }

    private long atime_ ;
    /**
     * <code>int64 atime = 12;</code>
     */
    public long getAtime() {
      return atime_;
    }
    /**
     * <code>int64 atime = 12;</code>
     */
    public Builder setAtime(long value) {
      
      atime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 atime = 12;</code>
     */
    public Builder clearAtime() {
      
      atime_ = 0L;
      onChanged();
      return this;
    }

    private long mtime_ ;
    /**
     * <code>int64 mtime = 13;</code>
     */
    public long getMtime() {
      return mtime_;
    }
    /**
     * <code>int64 mtime = 13;</code>
     */
    public Builder setMtime(long value) {
      
      mtime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 mtime = 13;</code>
     */
    public Builder clearMtime() {
      
      mtime_ = 0L;
      onChanged();
      return this;
    }

    private int redundancy_ = 0;
    /**
     * <code>.GrupoA.StorageController.gRPCService.FileSystem.RedundancyProto Redundancy = 14;</code>
     */
    public int getRedundancyValue() {
      return redundancy_;
    }
    /**
     * <code>.GrupoA.StorageController.gRPCService.FileSystem.RedundancyProto Redundancy = 14;</code>
     */
    public Builder setRedundancyValue(int value) {
      redundancy_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.GrupoA.StorageController.gRPCService.FileSystem.RedundancyProto Redundancy = 14;</code>
     */
    public GrupoA.StorageController.gRPCService.FileSystem.RedundancyProto getRedundancy() {
      @SuppressWarnings("deprecation")
      GrupoA.StorageController.gRPCService.FileSystem.RedundancyProto result = GrupoA.StorageController.gRPCService.FileSystem.RedundancyProto.valueOf(redundancy_);
      return result == null ? GrupoA.StorageController.gRPCService.FileSystem.RedundancyProto.UNRECOGNIZED : result;
    }
    /**
     * <code>.GrupoA.StorageController.gRPCService.FileSystem.RedundancyProto Redundancy = 14;</code>
     */
    public Builder setRedundancy(GrupoA.StorageController.gRPCService.FileSystem.RedundancyProto value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      redundancy_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.GrupoA.StorageController.gRPCService.FileSystem.RedundancyProto Redundancy = 14;</code>
     */
    public Builder clearRedundancy() {
      
      redundancy_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GrupoA.StorageController.gRPCService.FileSystem.iNodeAttributes)
  }

  // @@protoc_insertion_point(class_scope:GrupoA.StorageController.gRPCService.FileSystem.iNodeAttributes)
  private static final GrupoA.StorageController.gRPCService.FileSystem.iNodeAttributes DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new GrupoA.StorageController.gRPCService.FileSystem.iNodeAttributes();
  }

  public static GrupoA.StorageController.gRPCService.FileSystem.iNodeAttributes getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<iNodeAttributes>
      PARSER = new com.google.protobuf.AbstractParser<iNodeAttributes>() {
    @java.lang.Override
    public iNodeAttributes parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new iNodeAttributes(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<iNodeAttributes> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<iNodeAttributes> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public GrupoA.StorageController.gRPCService.FileSystem.iNodeAttributes getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

