// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FileSystem.proto

package GrupoA.StorageController.gRPCService.FileSystem;

public interface IntArgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GrupoA.StorageController.gRPCService.FileSystem.IntArg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 iNode = 1;</code>
   */
  int getINode();
}
