// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FileSystem.proto

package GrupoA.StorageController.gRPCService.FileSystem;

public interface LockResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GrupoA.StorageController.gRPCService.FileSystem.LockResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool Result = 1;</code>
   */
  boolean getResult();

  /**
   * <code>bool MapOutdated = 2;</code>
   */
  boolean getMapOutdated();
}
