// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FileSystem.proto

package GrupoA.StorageController.gRPCService.FileSystem;

public interface LongArgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GrupoA.StorageController.gRPCService.FileSystem.LongArg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 iNode = 1;</code>
   */
  long getINode();
}
