// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FileSystem.proto

package GrupoA.StorageController.gRPCService.FileSystem;

public interface MessageStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GrupoA.StorageController.gRPCService.FileSystem.MessageStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool FoundNode = 1;</code>
   */
  boolean getFoundNode();

  /**
   * <code>bool RequestCompleted = 2;</code>
   */
  boolean getRequestCompleted();
}
