// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FileSystem.proto

package GrupoA.StorageController.gRPCService.FileSystem;

public interface MetadaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GrupoA.StorageController.gRPCService.FileSystem.Metada)
    com.google.protobuf.MessageOrBuilder {
}
