// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FileSystem.proto

package GrupoA.StorageController.gRPCService.FileSystem;

public interface NodeArgsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GrupoA.StorageController.gRPCService.FileSystem.NodeArgs)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.GrupoA.StorageController.gRPCService.FileSystem.FileType type = 5;</code>
   */
  int getTypeValue();
  /**
   * <code>.GrupoA.StorageController.gRPCService.FileSystem.FileType type = 5;</code>
   */
  GrupoA.StorageController.gRPCService.FileSystem.FileType getType();

  /**
   * <code>string path = 1;</code>
   */
  java.lang.String getPath();
  /**
   * <code>string path = 1;</code>
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <code>int64 mode = 2;</code>
   */
  long getMode();

  /**
   * <code>int64 uid = 3;</code>
   */
  long getUid();

  /**
   * <code>int64 gid = 4;</code>
   */
  long getGid();

  /**
   * <code>int64 permissions = 6;</code>
   */
  long getPermissions();

  /**
   * <code>int64 creationTime = 7;</code>
   */
  long getCreationTime();

  /**
   * <code>.GrupoA.StorageController.gRPCService.FileSystem.RedundancyProto Redundancy = 8;</code>
   */
  int getRedundancyValue();
  /**
   * <code>.GrupoA.StorageController.gRPCService.FileSystem.RedundancyProto Redundancy = 8;</code>
   */
  GrupoA.StorageController.gRPCService.FileSystem.RedundancyProto getRedundancy();
}
