// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FileSystem.proto

package GrupoA.StorageController.gRPCService.FileSystem;

/**
 * Protobuf enum {@code GrupoA.StorageController.gRPCService.FileSystem.ProtoAttributeUpdateRequestType}
 */
public enum ProtoAttributeUpdateRequestType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>CHMOD = 0;</code>
   */
  CHMOD(0),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>CHMOD = 0;</code>
   */
  public static final int CHMOD_VALUE = 0;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ProtoAttributeUpdateRequestType valueOf(int value) {
    return forNumber(value);
  }

  public static ProtoAttributeUpdateRequestType forNumber(int value) {
    switch (value) {
      case 0: return CHMOD;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ProtoAttributeUpdateRequestType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ProtoAttributeUpdateRequestType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ProtoAttributeUpdateRequestType>() {
          public ProtoAttributeUpdateRequestType findValueByNumber(int number) {
            return ProtoAttributeUpdateRequestType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return GrupoA.StorageController.gRPCService.FileSystem.FileSystemProto.getDescriptor().getEnumTypes().get(1);
  }

  private static final ProtoAttributeUpdateRequestType[] VALUES = values();

  public static ProtoAttributeUpdateRequestType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ProtoAttributeUpdateRequestType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:GrupoA.StorageController.gRPCService.FileSystem.ProtoAttributeUpdateRequestType)
}

